services:
  - type: web
    name: yashraj-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start:api
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: API_PORT
        value: "5000"
